AllCops:
  NewCops: enable
Style/MethodMissingSuper:
  Enabled: false
Style/MissingRespondToMissing:
  Enabled: false
Layout/LineLength: 
  Max: 130
Metrics/BlockLength:
  Exclude:
    - '**/*_spec.rb'
