name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6

    - name: Cache bundle modules
      uses: actions/cache@v1
      env:
        cache-name: cache-bundle-modules
      with:
        path: ~/.bundle
        key: ${{ runner.os }}

    - name: Install dependencies
      run: bundle install

  rubocop:

    runs-on: ubuntu-latest
    needs: setup
    steps:
    - uses: actions/checkout@v2
      
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6

    - name: Cache bundle modules
      uses: actions/cache@v1
      env:
        cache-name: cache-bundle-modules
      with:
        path: ~/.bundle
        key: ${{ runner.os }}

    - name: Install dependencies
      run: bundle install

    - name: Run tests
      run: ./spec/run-test.sh rubocop

  rspec:

    runs-on: ubuntu-latest
    needs: setup
    steps:
    - uses: actions/checkout@v2
      
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6

    # - name: Cache bundle modules
    #   uses: actions/cache@v1
    #   env:
    #     cache-name: cache-bundle-modules
    #   with:
    #     path: ~/.bundle
    #     key: ${{ runner.os }}

    - name: Install dependencies
      run: bundle install

    - name: Run tests
      run: ./spec/run-test.sh rspec
